### ISSUE TITLE
MV fine details causes heavy dither like effect regardless of taa values on all aliased edges

### ISSUE THREAD

**Issue by ABdelrahmanAlaa1** [vortigern11/vort_Shaders#3] opened 2024-03-19 23:50 UTC
game is ac unity 
-disabled in game aa/ nv inspector all aa's for game 
-using smaa before taa
-enabling in game aa helps reduce to a bit but causes weird smearing

**Comment by vortigern11** [comment] 2024-03-20 13:39
If you disable SMAA, do you still have the issue?
If yes, then provide screenshots/videos of the following:
1) Example of everything working correctly before the "fine details" commit
2) Example of the issue caused by the "fine details" commit

**Comment by ABdelrahmanAlaa1** [comment] 2024-03-20 23:43
> If you disable SMAA, do you still have the issue? If yes, then provide screenshots/videos of the following:
> 
> 1. Example of everything working correctly before the "fine details" commit
> 2. Example of the issue caused by the "fine details" commit

ok tomorrow ill send you them (ill test the latest commit now and tell you if it is still present)

**Comment by ABdelrahmanAlaa1** [comment] 2024-03-20 23:59
still present and is more noticed with motion blur 
![ACU 2024-03-21 01-54-49](https://github.com/vortigern11/vort_Shaders/assets/159586604/1d152224-5c28-43ed-b76b-6c37bb958c70)
at any value  of motion blur regardless 0.01 or 2 and compute or not tried hw_lin on off same result, even tried different smaas still same issue enabled driver msaa and it got worse 
![ACU 2024-03-21 01-54-36](https://github.com/vortigern11/vort_Shaders/assets/159586604/51daa56e-5f28-4481-a37b-49ab315305c0)

![ACU 2024-03-21 01-54-28](https://github.com/vortigern11/vort_Shaders/assets/159586604/d10ad797-a616-41de-b9ac-4cf3bd8d3352)
![ACU 2024-03-21 01-51-02](https://github.com/vortigern11/vort_Shaders/assets/159586604/f7b00f6f-5978-462e-8324-0f7ec7e52642)
![ACU 2024-03-21 01-51-02 original](https://github.com/vortigern11/vort_Shaders/assets/159586604/097d7b1a-c037-4061-9857-f45c83967e6d)

![ACU 2024-03-21 01-50-59](https://github.com/vortigern11/vort_Shaders/assets/159586604/23aa2b99-e00e-4e88-938e-d8666f9efc00)
using immerse mv's at last image helps reduce it a bit but it wasn't present at all in older versions note only vort + smaa in this preset to test this issue

**Comment by ABdelrahmanAlaa1** [comment] 2024-03-21 00:01
![ACU 2024-03-21 01-50-59](https://github.com/vortigern11/vort_Shaders/assets/159586604/bc212ab7-4cc8-432d-bbb6-e4270d41ed57)
notice here any edges have dither (top)
![ACU 2024-03-21 01-50-59 original](https://github.com/vortigern11/vort_Shaders/assets/159586604/01c92868-cbf8-488a-a450-1632202a9c51) no dither here (off)

**Comment by ABdelrahmanAlaa1** [comment] 2024-03-21 00:01
- [ ] 

> ![ACU 2024-03-21 01-50-59](https://private-user-images.githubusercontent.com/159586604/314771386-bc212ab7-4cc8-432d-bbb6-e4270d41ed57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5Nzk1NjAsIm5iZiI6MTcxMDk3OTI2MCwicGF0aCI6Ii8xNTk1ODY2MDQvMzE0NzcxMzg2LWJjMjEyYWI3LTRjYzgtNDMyZC1iYmI2LWU0MjcwZDQxZWQ1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMVQwMDAxMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZGExNDRlMTlmNTlmMzBhYWViMjgwZTAxOGUxZmI4NTc3ZDM1MWJmNTI5ZDcyYTBiZDhhZDExNjFhOTJmZWE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.O-LCQ6XJRAhJeXzQ_pvqtGfSHeGnKSbBki7UYh4-LaM) notice here any edges have dither (top) ![ACU 2024-03-21 01-50-59 original](https://private-user-images.githubusercontent.com/159586604/314771410-01c92868-cbf8-488a-a450-1632202a9c51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5Nzk1NjAsIm5iZiI6MTcxMDk3OTI2MCwicGF0aCI6Ii8xNTk1ODY2MDQvMzE0NzcxNDEwLTAxYzkyODY4LWNiZjgtNDg4YS1hNDUwLTE2MzIyMDJhOWM1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMVQwMDAxMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MmMyZjg4ZWNlYWJmYWQ0Nzc1MjlmNWNjYmMyY2UyMWM5YzgwNjk3YWNmNGRhOTU1NDhhZDQzMzgxN2MyYTg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bKy4OP0vHVcOhTVg-pwmMfv4t1QwBb4j54A9KV5Hki4) no dither here (off)

this is with immerse with default or others it is much worse

**Comment by ABdelrahmanAlaa1** [comment] 2024-03-21 01:14
uber motion 2 has an unjitter toggle though uber motion is a messy blur with vort-motion the idea of unjitter is great for dlss/nis users and I use nis it had no issues with previous versions

**Comment by ABdelrahmanAlaa1** [comment] 2024-03-21 04:07
![image](https://github.com/vortigern11/vort_Shaders/assets/159586604/3b15a146-f31e-4f07-a5a9-011928ede35a)
![image](https://github.com/vortigern11/vort_Shaders/assets/159586604/9c3f9f00-c69e-47a9-8764-aa8a9308403c)
![image](https://github.com/vortigern11/vort_Shaders/assets/159586604/2aab1fb5-d24a-4a7d-8c49-0fe94382bc71)
![image](https://github.com/vortigern11/vort_Shaders/assets/159586604/6a375c35-0c03-4c62-8020-37031228a0cd)

**Comment by vortigern11** [comment] 2024-03-21 07:24
I removed my latest changes.
Tell me whether the issue is fixed now.

**Comment by ABdelrahmanAlaa1** [comment] 2024-03-21 22:51
great job it is much more tolerable  now but I feel motion blur got a bit weaker and less accurate on motion ( Ig due to reversing the last commit's changes)

**Comment by ABdelrahmanAlaa1** [comment] 2024-03-21 22:57
![ACU 2024-03-22 00-49-27](https://github.com/vortigern11/vort_Shaders/assets/159586604/a070ecd8-3ca6-4cb8-8277-e8cf6e786f93)
clean edges no weird dither
![ACU 2024-03-22 00-49-09](https://github.com/vortigern11/vort_Shaders/assets/159586604/89058c7c-e813-4b66-b345-ef8554823802)
It is still visible on heavy motion but I tuned mot blur to max; to check the issue you could reduce taa slightly based on how fast mouse movements are

**Comment by ABdelrahmanAlaa1** [comment] 2024-03-22 19:29
https://github.com/aestheticses/shaders-reshade/blob/main/MotionBlur.fx You could use this concept of mouse movement to reduce taa when heavy mouse movement is detected; or when the distance between past and current frame mv's is greater than a var that can be modified by a slider so, or even better a hybrid to fallback to the other one... ( this is for games which you can get velocity buffer for them using rest or have bugs with rest velocity like some ue4 games: octopath 1/2 flash on rest velocity setting)... this will tackle taa blur/ this dither like effect,

**Closed as completed** 2024-03-23 18:21 UTC
